version: "3.10"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/VCMS_API/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    expose:
      - 5432

volumes:
  postgres_data:
